Add note about persistent connections
couchbase/couchbase-php-client pull request #199
Opened 2024-12-05 18:20 UTC by avsej

This patch is related to [DOC-12803](https://jira.issues.couchbase.com/browse/DOC-12803). It documents INI options related to persistent connections.

More info about the concept is here: https://www.php.net/manual/en/features.persistent-connections.php

2024-12-05 18:54 UTC, raycardillo requested changes
Mostly grammar / readability corrections, but I tried to add a few small things for extra clarity as well.

2024-12-05 18:54 UTC, raycardillo commented on MIGRATION_FROM_3_x.md
> +instances. But instead running cleanup in the end of each request, it does
```suggestion
instances. But instead of running cleanup at the end of each request, it does
```

2024-12-05 18:54 UTC, raycardillo commented on MIGRATION_FROM_3_x.md
> +instance. In the end of each request, the SDK will run cleanup process that
```suggestion
instance. At the end of each request, the SDK runs a cleanup process that
```

2024-12-05 18:54 UTC, raycardillo commented on MIGRATION_FROM_3_x.md
> +counter reaches zero, the SDK records current time into idle timestamp of the
```suggestion
counter reaches zero, the SDK records the current time into idle timestamp of the
```

2024-12-05 18:54 UTC, raycardillo commented on MIGRATION_FROM_3_x.md
> +uniquely identified by connection string and credentials. When reference
```suggestion
uniquely identified by the connection string and credentials. When the reference
```

2024-12-05 18:54 UTC, raycardillo commented on MIGRATION_FROM_3_x.md
> +default is 60 seconds. The SDK associates reference counter with the instance
```suggestion
default is 60 seconds. The SDK associates a reference counter with the instance
```

2024-12-05 18:54 UTC, raycardillo commented on MIGRATION_FROM_3_x.md
> +Sets the interval that allowed for the persistent instance to be idle. The
```suggestion
Sets the maximum time that a persistent instance can be idle before being cleaned up. The
```

2024-12-05 18:54 UTC, raycardillo commented on MIGRATION_FROM_3_x.md
> +Sets the interval that allowed for the persistent instance to be idle. The
In the formatting, will it be clear that this was the PHP 3.2 way of setting this? Maybe we should add that to the description for clarity?

2024-12-05 18:54 UTC, raycardillo commented on MIGRATION_FROM_3_x.md
> +Persistent instances are useful for the cases that the PHP worker process is
```suggestion
Persistent instances are useful for cases when the PHP worker process is
```

2024-12-05 18:54 UTC, raycardillo commented on MIGRATION_FROM_3_x.md
> +not being destroyed after serving the request, so that next request will not
```suggestion
not destroyed after serving the request, so that next request will not
```

2024-12-05 18:54 UTC, raycardillo commented on MIGRATION_FROM_3_x.md
> +equal to `-1`, which means that the instances will be destroyed naturally
```suggestion
are set to `-1`, which means that the instances will be destroyed naturally
```

2024-12-05 18:54 UTC, raycardillo commented on MIGRATION_FROM_3_x.md
> +background threads, that can perform service tasks (like tracking configuration
```suggestion
background threads that can perform service tasks (like tracking configuration
```

2024-12-05 18:54 UTC, raycardillo commented on MIGRATION_FROM_3_x.md
> +So if `couchbase.max_persistent` is set to positive (or zero) value, the
```suggestion
So if `couchbase.max_persistent` is set to a positive (or zero) value, the
```

2024-12-05 18:54 UTC, raycardillo commented on MIGRATION_FROM_3_x.md
> +extension will run the cleanup tasks if number of existing instances, and will
```suggestion
extension will run the cleanup tasks if the number of existing instances exceeds the max, and will
```

2024-12-05 18:54 UTC, raycardillo commented on MIGRATION_FROM_3_x.md
> +destroy all instances, that have expired.
```suggestion
destroy all instances that have expired.
```

2024-12-05 18:54 UTC, raycardillo commented on MIGRATION_FROM_3_x.md
> +or pulled from the cache, and equals to current time plus
```suggestion
or pulled from the cache, and is set to the current time plus
```

2024-12-05 18:54 UTC, raycardillo commented on MIGRATION_FROM_3_x.md
> +For example, setting both `couchbase.persistent_timeout` and
```suggestion
Note that by setting both `couchbase.persistent_timeout` and
```

2024-12-05 18:54 UTC, raycardillo commented on MIGRATION_FROM_3_x.md
> +`couchbase.max_persistent` to zero will force extension to destroy all existing
```suggestion
`couchbase.max_persistent` to zero, this will force the extension to destroy all existing
```

2024-12-05 18:54 UTC, raycardillo commented on MIGRATION_FROM_3_x.md
> +connections and always create new one. So the application have to be extra
```suggestion
connections and always create a new one. If using this configuration, the application must be very
```

2024-12-05 18:54 UTC, raycardillo commented on MIGRATION_FROM_3_x.md
> +careful not to reuse destroyed connections by using equivalent of global
```suggestion
careful not to reuse destroyed connections, perhaps by using the equivalent of a global
```

2024-12-05 18:56 UTC, ingenthr requested changes
Thanks for doing this!  It's going to be a great doc improvement, but has a few issues at the moment.

2024-12-05 18:56 UTC, avsej commented on MIGRATION_FROM_3_x.md
> +Sets the interval that allowed for the persistent instance to be idle. The
It is rendered as a table column, so the left side is 3.x, right side is 4.x

2024-12-05 18:59 UTC, avsej commented on MIGRATION_FROM_3_x.md
> +<td>
This is just the place where I can describe both new and old behaviour. The idea is to reuse this content by @RichardSmedley's team on the documentation site

2024-12-05 19:01 UTC, avsej commented on MIGRATION_FROM_3_x.md
> +extension will run the cleanup tasks if number of existing instances, and will
Updated now. 
> if the number of existing instances exceeds the max

2024-12-05 19:49 UTC, avsej commented on MIGRATION_FROM_3_x.md
> +connections and always create new one. So the application have to be extra
no there is no special function. But we can implement something based on the usecase. Here the idea is that setting it to zero is not proper way to use it.

2024-12-05 23:33 UTC, avsej commented on MIGRATION_FROM_3_x.md
> +connections and always create new one. So the application have to be extra
In general these options are for advanced users, so if they know that whole web request will be served under a second, and expiration is higher than that, then they are safe.

The default `-1` is the safe option.

2024-12-06 13:37 UTC, RichardSmedley commented on MIGRATION_FROM_3_x.md
> +<td>
Thanks Sergey, this is a great start :+1:

2024-12-06 23:00 UTC, avsej commented on MIGRATION_FROM_3_x.md
> +connections and always create new one. So the application have to be extra
@raycardillo, @ingenthr this issue has been fixed in https://github.com/couchbase/couchbase-php-client/pull/200 (PCBC-1018).

2024-12-09 17:26 UTC, Matt-Woz commented on MIGRATION_FROM_3_x.md
> +cleanup only when the library need to create new connection and the number of
```suggestion
cleanup only when the library needs to create a new connection and the number of
```

2024-12-09 17:26 UTC, Matt-Woz commented on MIGRATION_FROM_3_x.md
> +need to wait for instance to bootstrap if it uses the same connection string,
```suggestion
need to wait for the instance to bootstrap if it uses the same connection string,
```

2024-12-09 17:36 UTC, Matt-Woz approved these changes

2024-12-09 17:41 UTC, merged