wrap user exceptions in transactions logic into TransactionException
couchbase/couchbase-php-client pull request #24
Opened 2022-05-03 12:42 UTC by avsej

2022-05-03 12:59 UTC, programmatix requested changes

2022-05-03 12:59 UTC, programmatix commented on Couchbase/Transactions.php
>                  $logic($transaction->transactionAttemptContext());
So is this loop the core loop?  https://hackmd.io/foGjnSSIQmqfks2lXwNp8w?view#The-Core-Loop
If so it looks like it's missing a great deal - e.g. there should be waits between retries, it should be deciding whether to retry in the first place, should be adding a cleanup request, lots more..  Is all of that in the C++, e.g. in $transaction->rollback/commit()?

2022-05-03 13:26 UTC, avsej commented on Couchbase/Transactions.php
>                  $logic($transaction->transactionAttemptContext());
I took this code from @brett19's couchnode, so I'd assume that all those things you are talking about are done in C++ transactions. @davidkelly can confirm

https://github.com/couchbase/couchnode/blob/9119eca7e96ed2735475cb488ceb3e6da09849d4/lib/transactions.ts#L674-L695

```js
    for (;;) {
      await txn._newAttempt()

      try {
        await logicFn(txn)
      } catch (e) {
        await txn._rollback()
        throw e
      }

      try {
        const txnResult = await txn._commit() // this is actually finalize internally
        if (!txnResult) {
          // no result and no error, try again
          continue
        }

        return txnResult
      } catch (e) {
        // commit failed, retry...
      }
    }
```

2022-05-03 13:27 UTC, avsej commented on Couchbase/Transactions.php
>                  $logic($transaction->transactionAttemptContext());
oh, and btw you can see that node.js just re-throws `e` and does not wrap it.

2022-05-03 16:34 UTC, avsej commented on Couchbase/Transactions.php
> +                throw new TransactionException("Exception caught during execution of transaction logic", 0, $exception);
I've fixed it. Now it wraps with `TransactionFailedException`

2022-05-05 11:15 UTC, programmatix commented on Couchbase/Transactions.php
>                  $logic($transaction->transactionAttemptContext());
Actually I do now recall some discussion with Brett about him moving the core loop logic in Go into commit() and rollback().  As long as all the functionality of the core loop is ultimately implemented, that's what matters.

2022-05-05 13:25 UTC, programmatix approved these changes
Approving, but somewhat reluctantly as it's hard for me to perform a good review here.  As below, I think we need to start testing the wrappers in FIT to ensure the behaviour is correctly implemented.

2022-05-05 13:25 UTC, programmatix commented on Couchbase/Transactions.php
> +                throw new TransactionFailedException("Exception caught during execution of transaction logic", 0, $exception);
This bit is hard to review, without knowing the internal machinery of C++, as it doesn't really map to the specced logic.  It looks like it might be doing the https://hackmd.io/foGjnSSIQmqfks2lXwNp8w#Exceptions-Raised-by-the-Application-Lambda part of the spec.  If so then the logic here isn't correct - a TransactionOperationFailedException should be getting raised, after setting internal state to e.g. prevent other operations, and handled later by the core loop.  However, I can also see how ultimately it may result in the same behaviour to the user, so it _may_ be correct - as I say, hard for me to review.

I increasingly think we need to be putting the wrappers through at least a subset of the FIT tests - those ones checking errors are handled correctly, that config values are passed through, those kinds of things.  Because I'm nervous about how hard it is for me to, at a glance, tell if the wrappers are correctly implementing the specced behaviour.  This 'FIT lite' idea has been thrown around for a while now.

I think this looks like it will at least result in 'close enough' behaviour, and if not then any impact should be limited to this implementation (e.g. it's not affecting what's written on the wire), so I'm not going to -2 because of it.  But yeah - let's get some FIT testing going, to build confidence.

2022-05-05 13:28 UTC, avsej commented on src/core/transaction_context_resource.cxx
> +        } catch (const couchbase::transactions::transaction_exception& e) {
we probably cleanup style of transactions API when it will be dissolved in C++SDK

2022-05-05 13:29 UTC, merged