PCBC-865: prefer CMAKE_BUILD_PARALLEL_LEVEL to hardcoded --parallel switch
couchbase/couchbase-php-client pull request #33
Opened 2022-05-30 18:27 UTC by avsej

2022-05-31 12:42 UTC, chvck requested changes

2022-05-31 12:42 UTC, chvck commented on bin/build
> +  ENV["CMAKE_BUILD_PARALLEL_LEVEL"] = ENV.fetch("CB_NUBMER_OF_JOBS", "4")
Should this be `CB_NUMBER_OF_JOBS` rather than `CB_NUBMER_OF_JOBS`

2022-06-01 14:25 UTC, avsej commented on bin/build
> +  ENV["CMAKE_BUILD_PARALLEL_LEVEL"] = ENV.fetch("CB_NUBMER_OF_JOBS", "4")
Thanks

2022-07-28 18:10 UTC, brett19 submitted a review, later dismissed

2022-07-28 18:16 UTC, merged